# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wongkx.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Kevin Wong
  avatar: #
  gravatar: 345c98b9da5c86d7b2fb79bce2873f29
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Designer, Developer, Thinker...</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "kevinwong6175@gmail.com"
  behance:
  bitbucket:
  dribbble: # username
  facebook: "k3v1nw0ng"
  flickr:
  github: "madebymunsters/type-theme"
  google_plus:
  instagram: "wongkx"
  linkedin:  "linkedin.com/in/kevin-wong-a10ba323"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # username
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-100072198-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]